---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-server
  labels:
    project: fourtimes
    tier: db
spec:
  serviceName: db-server-service
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: api-server
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: db-secret
      #   volumeMounts:
      #   - name: dbdata
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: dbdata
      #   persistentVolumeClaim:
      #     claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-server-service
  labels:
    project: fourtimes
    tier: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 3306

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    project: fourtimes
    tier: db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Zm91cnRpbWVz
  MYSQL_USER: Zm91cnRpbWVz
  MYSQL_PASSWORD: Zm91cnRpbWVz
  MYSQL_DATABASE: Zm91cnRpbWVz

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: db-storage-class
  labels:
    project: fourtimes
    tier: db
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    project: fourtimes
    tier: db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: db-storage-class
  resources:
    requests:
      storage: 7Gi